// 在这个文件中，你只需要存放招聘信息数据。
// 将来更新时，只需修改此文件即可。

const jobData = [
    { company: "北京市疾病预防控制中心", type: "事业单位", industry: "医疗/公共卫生", recruitmentType: "秋招", location: "北京", target: "2025年毕业生", position: "病原微生物检验及生物信息学应用、免疫、生化检验检测、内部审计管理", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://rsj.beijing.gov.cn/xxgk/gkzp/202508/t20250814_4172939.html", announcementLink: "https://rsj.beijing.gov.cn/xxgk/gkzp/202508/t20250814_4172939.html", referralCode: "-", notes: "硕士研究生及以上" },
                { company: "海南卫生健康职业学院", type: "事业单位", industry: "教育", recruitmentType: "秋招", location: "海南", target: "2026年毕业生", position: "思政教师、体育教师、辅导员", status: "未投递", updateTime: "2025-08-16", deadline: "2025-09-30", applyLink: "http://zp.cpta.com.cn/tyzpwb/?examid=dbdGdb", announcementLink: "https://hrss.hainan.gov.cn/hrss/sydwzp/202508/0d72715852864a8a8096f51c8f155a6a.shtml", referralCode: "-", notes: "硕士研究生及以上" },
                { company: "南京信息职业技术学院", type: "事业单位", industry: "教育", recruitmentType: "秋招", location: "江苏", target: "2025年毕业生", position: "教师", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://rs.jshrss.jiangsu.gov.cn/index/f/RCRS_0056", announcementLink: "https://jshrss.jiangsu.gov.cn/art/2025/8/14/art_78506_11623350.html", referralCode: "-", notes: "-" },
                { company: "苏州数智科技集团", type: "央国企", industry: "信息技术", recruitmentType: "秋招", location: "苏州", target: "2026年毕业生", position: "人工智能工程师、解决方案工程师、数据开发工程师等", status: "未投递", updateTime: "2025-08-16", deadline: "2025-10-15", applyLink: "https://mp.weixin.qq.com/s/i6EmiqGRpyHM-mEl2n8y7w", announcementLink: "https://mp.weixin.qq.com/s/i6EmiqGRpyHM-mEl2n8y7w", referralCode: "-", notes: "-" },
                { company: "江苏国信数智服务", type: "央国企", industry: "信息技术", recruitmentType: "秋招", location: "江苏", target: "2026年毕业生", position: "系统工程师、综合部综合业务岗", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/iW2VAufCq0vmfvlcni032A", announcementLink: "https://mp.weixin.qq.com/s/iW2VAufCq0vmfvlcni032A", referralCode: "-", notes: "-" },
                { company: "四川省水电投资经营集团", type: "央国企", industry: "能源/电气", recruitmentType: "秋招", location: "四川", target: "2026年毕业生", position: "应急与安全环保岗、配电运检员", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/poPqvq4TbEjHzSNwLBV8pw", announcementLink: "https://mp.weixin.qq.com/s/poPqvq4TbEjHzSNwLBV8pw", referralCode: "-", notes: "-" },
                { company: "深信服", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "多地", target: "2026年毕业生", position: "研发类、市场类、技术类、职能类", status: "未投递", updateTime: "2025-08-16", deadline: "2025-11-01", applyLink: "https://app.mokahr.com/campus_apply/sangfor/27944?sessionid=#/", announcementLink: "https://mp.weixin.qq.com/s/qhjffwymFjvv0dDp8T2PZA", referralCode: "-", notes: "-" },
                { company: "炬芯科技", type: "民企", industry: "半导体", recruitmentType: "秋招", location: "珠海,成都,合肥", target: "2026年毕业生", position: "模拟电路设计、数字电路设计、嵌入式软件工程师等", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://actionstech.zhiye.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/KZ0dUDKJw93nuDf6oiXC1w", referralCode: "-", notes: "要求硕士" },
                { company: "收钱吧", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "上海,苏州,杭州", target: "2026年毕业生", position: "技术类、运营类、职能类、市场类", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://shouqianba.zhiye.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/BOFE6kVbqiTWr0MP-hXhPQ", referralCode: "-", notes: "-" },
                { company: "安克创新", type: "民企", industry: "消费电子", recruitmentType: "秋招", location: "多地", target: "2026年毕业生", position: "技术族、营销族、产品族、设计族等", status: "未投递", updateTime: "2025-08-16", deadline: "2025-10-31", applyLink: "https://anker-in.jobs.feishu.cn/campushirecn/?project=7537217835232594215", announcementLink: "https://mp.weixin.qq.com/s/8vFDBIzY2ar97VX8iffDRQ", referralCode: "-", notes: "-" },
                { company: "顾家家居", type: "民企", industry: "家居", recruitmentType: "秋招", location: "多地", target: "2026年毕业生", position: "设计类、信息技术类、研发技术类、营销类", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/kuka/150858", announcementLink: "https://mp.weixin.qq.com/s/1r4TNT3hz6Y_zLo0KKsP3Q", referralCode: "-", notes: "-" },
                { company: "上海空间电源研究所", type: "事业单位", industry: "科研", recruitmentType: "秋招", location: "上海", target: "2026年毕业生", position: "电子电源研究师、化学电源研究师等", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://sast.m.zhiye.com/job.html?jc=2", announcementLink: "https://mp.weixin.qq.com/s/ox8-uHtnBlClShbQPxQezQ", referralCode: "-", notes: "要求硕士" },
                { company: "华为", type: "民企", industry: "通信/半导体", recruitmentType: "秋招", location: "多地", target: "2026年毕业生", position: "研发类、销售类、财经类、供应链类", status: "未投递", updateTime: "2025-08-16", deadline: "2025-10-20", applyLink: "https://career.huawei.com/reccampportal/portal5/campus-recruitment.html", announcementLink: "https://mp.weixin.qq.com/s/fgmQPCD6j-VD-S2FezhbLg", referralCode: "-", notes: "-" },
                { company: "钜泉科技", type: "民企", industry: "半导体", recruitmentType: "秋招", location: "上海,西安", target: "2026年毕业生", position: "模拟设计、数字设计、算法工程师等", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://hitrendtech1.zhiye.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/CF5LMxS5miZcMv0DKiToOw", referralCode: "-", notes: "-" },
                { company: "麦捷科技", type: "民企", industry: "半导体", recruitmentType: "秋招", location: "深圳", target: "2026年毕业生", position: "技术研发、助理工程师、FAE工程师等", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/4PhVP9JFSAcLOExSwf7bTA", announcementLink: "https://mp.weixin.qq.com/s/4PhVP9JFSAcLOExSwf7bTA", referralCode: "-", notes: "-" },
                { company: "长沙矿山研究院", type: "央国企", industry: "矿产", recruitmentType: "秋招", location: "长沙", target: "2026年毕业生", position: "矿业类、机电类、自动化类、计算机类", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/DifL3rtj--vdlwL3yE2smw", announcementLink: "https://mp.weixin.qq.com/s/DifL3rtj--vdlwL3yE2smw", referralCode: "-", notes: "-" },
                { company: "中汇会计师事务所", type: "民企", industry: "咨询", recruitmentType: "秋招", location: "多地", target: "2026年毕业生", position: "审计岗、税务岗、金融咨询岗等", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "http://zhaopin.zhcpa.cn/list-163-1.html", announcementLink: "https://mp.weixin.qq.com/s/8KdoGajIxnt5sxm0OUCXMg", referralCode: "-", notes: "-" },
                { company: "嘉实基金", type: "民企", industry: "金融", recruitmentType: "秋招提前批", location: "北京", target: "2026年毕业生", position: "算法工程师、开发工程师、数据工程师等", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://harvestgroup.wjx.cn/vm/eUlhtLO.aspx", announcementLink: "https://mp.weixin.qq.com/s/Gj1BIsfk-Cfb737xX7r9aA", referralCode: "-", notes: "-" },
                { company: "康冠科技", type: "民企", industry: "半导体", recruitmentType: "秋招", location: "深圳,惠州", target: "2026年毕业生", position: "博士专项、算法与软件开发、硬件研发等", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://careerktc.zhiye.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/QvK0kXlDa29CVfeRWL13Iw", referralCode: "-", notes: "-" },
                { company: "顺络电子", type: "民企", industry: "半导体", recruitmentType: "秋招提前批", location: "东莞,深圳", target: "2026年毕业生", position: "材料工程师、研发工程师、装备研发工程师", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/sunlord/142929", announcementLink: "https://mp.weixin.qq.com/s/x_oY9YAPfEhdJazDzQpQTw", referralCode: "-", notes: "-" },
                { company: "虹科", type: "民企", industry: "半导体", recruitmentType: "秋招", location: "多地", target: "2026年毕业生", position: "技术研发、销售、市场、产品管培生", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://hkaco.zhiye.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/UpbrhjAasnLPLDFxCnQWxQ", referralCode: "-", notes: "-" },
                { company: "网易-星火计划", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "杭州,广州,上海", target: "2026年毕业生", position: "人力资源培训生", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://campus.163.com/app/detail/index?id=3279&projectId=67", announcementLink: "https://mp.weixin.qq.com/s/4aSQsWzKlX4wQ5qn7eX-pg", referralCode: "-", notes: "-" },
                { company: "新能安A+Star", type: "民企", industry: "能源/电力", recruitmentType: "秋招", location: "厦门", target: "2026年毕业生", position: "博士专项、材料电芯研发、电源电子研发等", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://ampace.hotjob.cn/", announcementLink: "https://mp.weixin.qq.com/s/FIguF2udNFVUOb5Z0JCkNg", referralCode: "-", notes: "-" },
                { company: "库犸科技", type: "民企", industry: "机器人", recruitmentType: "秋招", location: "深圳,成都", target: "2026年毕业生", position: "技术类岗位、非技术类岗位", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/mammotion/148030", announcementLink: "https://mp.weixin.qq.com/s/_59qIoNPNHRy_vr6AlzSMA", referralCode: "-", notes: "-" },
                { company: "纳芯微", type: "民企", industry: "半导体", recruitmentType: "秋招", location: "多地", target: "2026年毕业生", position: "研发类、营销类、运营类、质量类", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://www.moseeker.com/positions/index/cid/5553471", announcementLink: "https://mp.weixin.qq.com/s/G4Nz9LYXdsDT7SEZHf-7TQ", referralCode: "-", notes: "-" },
                { company: "优优绿能", type: "民企", industry: "能源/电力", recruitmentType: "秋招", location: "深圳", target: "2026年毕业生", position: "预研工程师、结构工程师、DSP软件工程师等", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/rKidAXJ-W1DBxf6l-IRhUQ", announcementLink: "https://mp.weixin.qq.com/s/rKidAXJ-W1DBxf6l-IRhUQ", referralCode: "-", notes: "-" },
                { company: "联友科技", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "多地", target: "2026年毕业生", position: "AI类、数据类、软件设施类、体验设计类", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://szly.zhiye.com/campus", announcementLink: "https://mp.weixin.qq.com/s/_aSVs8UiZ7yxZgKXUQZEXA", referralCode: "-", notes: "-" },
                { company: "英伟芯", type: "民企", industry: "半导体", recruitmentType: "秋招", location: "上海,西安", target: "2026年毕业生", position: "硬件工程师、固件工程师、系统工程师等", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/r91e-HOxkNzDA_zosWQh0g", announcementLink: "https://mp.weixin.qq.com/s/r91e-HOxkNzDA_zosWQh0g", referralCode: "-", notes: "-" },
                { company: "传音控股", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "上海,深圳,重庆", target: "2025/2026届", position: "算法工程师、影音算法工程师", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://transsion.zhiye.com/4/jobs?sessionid=", announcementLink: "https://mp.weixin.qq.com/s/Do4PhVT8OYexC7S5FkBGCg", referralCode: "-", notes: "要求硕士" },
                { company: "直真科技", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "多地", target: "2026年毕业生", position: "大模型算法工程师、前后端开发、产品经理等", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/Sp7rkigj0QTtn1h5L6R6Pg", announcementLink: "https://mp.weixin.qq.com/s/Sp7rkigj0QTtn1h5L6R6Pg", referralCode: "-", notes: "-" },
                {
                    company: "BCG中国区欧洲院校",
                    type: "外企",
                    industry: "商务服务/咨询",
                    recruitmentType: "秋招",
                    location: "北京 上海深圳香港台北",
                    target: "2026年毕业生",
                    position: "2026届欧洲院校本科生、硕士研究生、博士生和MBA",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://careers.bcg.com/global/en/job/54953",
                    announcementLink: "https://mp.weixin.qq.com/s/Yf-ku2aQCXmQ9YKtIMRyMg",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "国机数字科技有限公司",
                    type: "央国企",
                    industry: "IT/互联网",
                    recruitmentType: "秋招",
                    location: "南京北京郑州",
                    target: "2026年毕业生",
                    position: "软件开发工程师 前端开发工程师 智能算法工程师 智能硬件工程师解决方案助理战略理岗",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://webapp.zhaopin.com/2025/hd/gjszk0814ZL68537/xJobs/index.html",
                    announcementLink: "https://mp.weixin.qq.com/s/E32wOHBpasPQZHud7QWc4g",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "同道猎聘",
                    type: "民企",
                    industry: "IT/互联网",
                    recruitmentType: "秋招",
                    location: "北京武汉 成都杭州苏州 广州",
                    target: "2026年毕业生",
                    position: "产品类技术研发类运营类市场类销售类",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://www.liepin.com/logout?backUrl=httpsm.liepin.comcampusproject-detail14068724sessionid",
                    announcementLink: "https://mp.weixin.qq.com/s/-vUkYCVUYvaFKAdupmIdcg",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "新国都集团",
                    type: "民企",
                    industry: "IT/互联网",
                    recruitmentType: "秋招",
                    location: "深圳",
                    target: "2026年毕业生",
                    position: "渠道助理产品经理JAVA开发工程师网络安全工程师区块链开发工程师通信嵌入式工程师;",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://app.mokahr.com/campus-recruitment/xgd/7850?sessionid=&sourceToken=9b501cf30474b6d448492f12db68c7b3#/",
                    announcementLink: "https://mp.weixin.qq.com/s/b6BkSVGjmyveCpe3QfqTKg",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "中国航空制造技术研究院",
                    type: "事业单位",
                    industry: "学术科研/研究所",
                    recruitmentType: "秋招",
                    location: "北京",
                    target: "2026年毕业生",
                    position: "材料类机械工程类学类光学工程类自动化类化学类电子科学与技术类机械类航空字航科学与技术类 数学类等",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://avicmti.zhiye.com/campus/jobs",
                    announcementLink: "https://mp.weixin.qq.com/s/dGnnG1-pc0rmNve_eq6Nfw",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "中国电科第十四研究所",
                    type: "事业单位",
                    industry: "学术科研/研究所",
                    recruitmentType: "秋招",
                    location: "南京",
                    target: "2026年毕业生",
                    position: "电子与通信类计算机类机械与控制类其他类;",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "http://hr.nriet.com/Pages/Job/Jobs.aspx",
                    announcementLink: "https://mp.weixin.qq.com/s/H8dP8O9Bw_Ji2WhBM6VS4A",
                    referralCode: "-",
                    notes: "要求硕士"
                },
                {
                    company: "中国电科29所",
                    type: "事业单位",
                    industry: "学术科研/研究所",
                    recruitmentType: "秋招",
                    location: "成都",
                    target: "2026年毕业生",
                    position: "电子与通信类专业计算机与软件类专业控制与仪器类专业机械与工程类专业其他类专业",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://campus.51job.com/cetc29/company.html",
                    announcementLink: "https://mp.weixin.qq.com/s/r_xbvmnHw3Hu5vMZlniKkQ",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "开立医疗",
                    type: "民企",
                    industry: "生物制药/生命科学",
                    recruitmentType: "秋招",
                    location: "深圳武汉北京上海",
                    target: "2026年毕业生",
                    position: "研发技术类 营销用服类",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://campus.sonoscape.com/campus-recruitment/sonoscape/94392/#/",
                    announcementLink: "https://mp.weixin.qq.com/s/wvblbhGG3kGMDnZ8JJxsJQ",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "华为财经",
                    type: "民企",
                    industry: "商务服务/咨询",
                    recruitmentType: "秋招",
                    location: "深圳",
                    target: "2026年毕业生",
                    position: "财经专员",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://career.huawei.com/reccampportal/portal5/campus-recruitment-detail.html?jobId=24310&dataSource=1&jobType=0&recruitType=CR&sourceType=001",
                    announcementLink: "https://mp.weixin.qq.com/s/74xjr0HcgRp59sm7qjmyZg",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "埃特曼半导体",
                    type: "民企",
                    industry: "电子技术/半导体",
                    recruitmentType: "秋招",
                    location: "厦门",
                    target: "2026年毕业生",
                    position: "材料外延研发材料外延材料测试机械设计电气设备装调市场营销董事长助理董事长英文助理;",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://mp.weixin.qq.com/s/XUkj1ImVsicuVH56Q82WLA",
                    announcementLink: "https://mp.weixin.qq.com/s/XUkj1ImVsicuVH56Q82WLA",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "台达-研发岗",
                    type: "民企",
                    industry: "电子技术/半导体",
                    recruitmentType: "秋招",
                    location: "上海 武汉杭州等",
                    target: "2026年毕业生",
                    position: "电力电子研发设计工程师韧体控制工程师电源嵌入式软件设计工程师;",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://www.wjx.cn/vm/meczbLI.aspx",
                    announcementLink: "https://mp.weixin.qq.com/s/LUxENTqtWuRu-ooa5YP4eA",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "宁德新能源",
                    type: "民企",
                    industry: "能源/电力",
                    recruitmentType: "秋招",
                    location: "宁德",
                    target: "2026年毕业生",
                    position: "材料/电芯研发类项目/运营类IT/大数据类博士专项机械/电气研发类智能制造类职能类 海外专项;",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://wecruit.hotjob.cn/SU5ff30f5b9b0d78e6f4283a0b/pb/school.html",
                    announcementLink: "https://mp.weixin.qq.com/s/ffZdqoY_Mzj17ez3wQe3wA",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "开开华彩",
                    type: "民企",
                    industry: "教育",
                    recruitmentType: "秋招",
                    location: "北京成都",
                    target: "2026年毕业生",
                    position: "线上主讲类线下主讲类二讲老师类学习顾问类 运营类管培生;",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://kn50h9mzpl.jobs.feishu.cn/891492/position/list?sessionid=",
                    announcementLink: "https://mp.weixin.qq.com/s/zz0IGP-yjHrugnF0UJsrlw",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "点触科技",
                    type: "民企",
                    industry: "IT/互联网",
                    recruitmentType: "秋招",
                    location: "厦门",
                    target: "2026年毕业生",
                    position: "游戏策划客服翻译营销策划 后端研发工程师测试工程师移动前端工程师 广告设计师视频设计师场景原画设计师等",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://zhaopin.dianchu.com/CampusRecruitment",
                    announcementLink: "https://zhaopin.dianchu.com/CampusRecruitment",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "明汯投资",
                    type: "民企",
                    industry: "金融/证券",
                    recruitmentType: "秋招",
                    location: "香港 上海北京",
                    target: "2026年毕业生",
                    position: "量化研究员AI算法研究员量化开发工程师AI基础架构开发工程师",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://join.mhfunds.com/index",
                    announcementLink: "https://mp.weixin.qq.com/s/9j-wM2GUBQR0F_Tbjt7f1w",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "OBSBOT寻影",
                    type: "民企",
                    industry: "电子技术/半导体",
                    recruitmentType: "秋招",
                    location: "深圳成都杭州",
                    target: "2026年毕业生",
                    position: "研发类非研发类管培生计划",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://www.obsbot.cn/cn/about/careers",
                    announcementLink: "https://mp.weixin.qq.com/s/OIKoSfcBIZNbURSZtWt-pg",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "瑞银",
                    type: "外企",
                    industry: "金融/证券",
                    recruitmentType: "秋招",
                    location: "北京 上海",
                    target: "2026年毕业生",
                    position: "管理培训生",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://mp.weixin.qq.com/s/xrpEqltPQGpYNDadLsKEfw",
                    announcementLink: "https://mp.weixin.qq.com/s/xrpEqltPQGpYNDadLsKEfw",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "度小满",
                    type: "民企",
                    industry: "IT/互联网",
                    recruitmentType: "秋招",
                    location: "北京 上海",
                    target: "2026年毕业生",
                    position: "算法类 研发类 产品类 运营类风险管理类商业分析类 设计类职能类;",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://campus.duxiaoman.com/051736/position/list?keywords=&category=&location=&project=7525275560747993382&type=&job_hot_flag=&current=1&limit=10&functionCategory=&tag=",
                    announcementLink: "https://mp.weixin.qq.com/s/kFAAdWPrkGEYyQrYd6YH0w",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "中国电信天翼云",
                    type: "央国企",
                    industry: "通信服务/电信运营",
                    recruitmentType: "秋招",
                    location: "北京 上海广州深圳成都 厦门",
                    target: "2026年毕业生",
                    position: "云计算研究员后端开发工程师硬件开发工程师 客户端开发工程师 测试开发工程师解决方案经理 算法工程师等",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://wecruit.hotjob.cn/SU62b2ae672f9d24458d72f9cc/pb/school.html",
                    announcementLink: "https://mp.weixin.qq.com/s/RWvR_-S4H6yOUcKk58GTGg",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "豪威集团",
                    type: "民企",
                    industry: "电子技术/半导体",
                    recruitmentType: "秋招",
                    location: "上海北京 天津 武汉成都 哈尔滨",
                    target: "2026年毕业生",
                    position: "数字电路设计工程师模拟IC设计工程师数字电路后端设计工程师数字验证工程师DFTI程师信号完整性工程师",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://ovt-omnivision.zhiye.com/Campus",
                    announcementLink: "https://mp.weixin.qq.com/s/2eiOj8wkdJjrOMrtT6CA7Q",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "TP-Link联洲",
                    type: "民企",
                    industry: "通信服务/电信运营",
                    recruitmentType: "秋招",
                    location: "国外",
                    target: "2026年毕业生",
                    position: "国际业务管理培训生",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://career.tplinkglobal.com/campus/jobs?sessionid=",
                    announcementLink: "https://mp.weixin.qq.com/s/iAwFk3Lm1PZ7z-lHiK27Vg",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "国仪量子",
                    type: "民企",
                    industry: "机械装备/电气系统",
                    recruitmentType: "秋招",
                    location: "合肥 广州杭州苏州无锡",
                    target: "2026年毕业生",
                    position: "应用工程师服务工程师客户成功经理系统工程师 结构工程师 硬件工程师软件工程师嵌入式软件工程师电子光学工程师高级系统工程师 算法工程师等",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://mp.weixin.qq.com/s/UsUSFs6jYp0fkqzi0T2crQ",
                    announcementLink: "https://mp.weixin.qq.com/s/UsUSFs6jYp0fkqzi0T2crQ",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "海尼集团",
                    type: "民企",
                    industry: "电商/跨境电商",
                    recruitmentType: "秋招",
                    location: "厦门广州杭州",
                    target: "2026年毕业生",
                    position: "电商运营方向新媒体内客方向IT方向产品研发方向供应链方向市场与商务方向视觉设计方向 职能方向;",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://test-recruit.xmhaini.com/?sessionid=",
                    announcementLink: "https://mp.weixin.qq.com/s/tcOhxQOGCYMrviI-7W7FDw",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "星火教育",
                    type: "民企",
                    industry: "教育",
                    recruitmentType: "秋招",
                    location: "全国",
                    target: "2026年毕业生",
                    position: "精品课堂教学管培生，授课学科:语文、数学、英语、物理、化学;",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://mp.weixin.qq.com/s/Qu4Tt_9t_hdSAMMw7qgUCg",
                    announcementLink: "https://mp.weixin.qq.com/s/Qu4Tt_9t_hdSAMMw7qgUCg",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "飞仕得",
                    type: "民企",
                    industry: "能源/电力",
                    recruitmentType: "秋招",
                    location: "杭州",
                    target: "2026年毕业生",
                    position: "电力电子工程师器件工程师 上位机软件工程师硬件工程师电源工程师等",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://app135149.dingtalkoxm.com/campus-recruitment/ding-pay-yhdjz66b/100000394?locale=zh-CN#/",
                    announcementLink: "https://mp.weixin.qq.com/s/N3H-wl8ZF1a-FPIrlUvY1A",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "联合电子",
                    type: "民企",
                    industry: "车企/汽车零部件",
                    recruitmentType: "秋招",
                    location: "上海重庆 太仓芜湖无锡苏州柳州",
                    target: "2026年毕业生",
                    position: "产品研发 智能制造 供应链管理 质量管理营理培训生 项目管理;",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://campus.51job.com/uaes2026/jobs.html",
                    announcementLink: "https://mp.weixin.qq.com/s/q-Sf12E2t-CiZnIDyGKGQQ",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "震坤行",
                    type: "民企",
                    industry: "IT/互联网",
                    recruitmentType: "秋招",
                    location: "上海北京广东江苏浙江 甘肃 新疆 陕西山东湖北全国其他",
                    target: "2026年毕业生",
                    position: "销服类供应链类软件研发类硬件研发类;",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://zhaopin.zkh.com/campus/jobs",
                    announcementLink: "https://mp.weixin.qq.com/s/syGrywCVaBYZZxyM3M6vfw",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "沁恒微电子",
                    type: "民企",
                    industry: "电子技术/半导体",
                    recruitmentType: "秋招",
                    location: "南京",
                    target: "2026年毕业生",
                    position: "数字IC设计工程师数字IC设计工程师 模拟射频IC设计工程师基带算法工程师嵌入式开发工程师 协议栈开发工程师等",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://mp.weixin.qq.com/s/tSnZCfQ9WkluW-fbg-0Jnw",
                    announcementLink: "https://mp.weixin.qq.com/s/tSnZCfQ9WkluW-fbg-0Jnw",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "步科股份",
                    type: "民企",
                    industry: "机器人/无人机",
                    recruitmentType: "秋招",
                    location: "常州成都上海深圳",
                    target: "2026年毕业生",
                    position: "软件工程师 应用工程师 硬件工程师 结构工程师电磁工程师 测试工程师 电子测试工程师市场销售类采购工程师等",
                    status: "未投递",
                    updateTime: "2025-08-17",
                    deadline: "招满为止",
                    applyLink: "https://s.xinrenxinshi.com/recruitGate/list#/ey=0ebdb20c8a4f7c6f8f15cca6c3375e4785c467",
                    announcementLink: "https://mp.weixin.qq.com/s/K0Xk7LXL9Y0pDDE_Z80gKw",
                    referralCode: "-",
                    notes: "-"
                },
                {
                    company: "北京市疾病预防控制中心",
                    type: "事业单位",
                    industry: "医疗/公共卫生",
                    recruitmentType: "秋招",
                    location: "北京",
                    target: "2025年毕业生",
                    position: "病原微生物检验及生物信息学应用、免疫、生化检验检测、内部审计管理",
                    status: "未投递",
                    updateTime: "2025-08-16",
                    deadline: "招满为止",
                    applyLink: "https://rsj.beijing.gov.cn/xxgk/gkzp/202508/t20250814_4172939.html",
                    announcementLink: "https://rsj.beijing.gov.cn/xxgk/gkzp/202508/t20250814_4172939.html",
                    referralCode: "-",
                    notes: "硕士研究生及以上"
                },
                {company: "禾望电气", type: "民企", industry: "能源/电力", recruitmentType: "秋招", location: "深圳西安苏州武汉", target: "2026年毕业生", position: "电力电子硬件工程师 电力电子软件工程师嵌入式软件工程师前端开发工程师 后端开发工程师 AI开发工程师 桌面软件工程师结构工程师市场管培生等", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/4LRBxxC64VjDf7BQT_3Myg", announcementLink: "https://mp.weixin.qq.com/s/4LRBxxC64VjDf7BQT_3Myg", referralCode: "-", notes: "-"},
                {company: "信锐技术", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "深圳全国其他", target: "2026年毕业生", position: "客户经理 售前产品经理技术服务工程师C/C++软件开发工程师，", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://hr.sundray.com.cn/campus-recruitment/sangfor/37521#/jobs", announcementLink: "https://mp.weixin.qq.com/s/5w57o_XGn5B6hn4Iy2j0yA", referralCode: "-", notes: "-"},
{company: "沃尔玛中国", type: "外企", industry: "酒店/餐饮", recruitmentType: "秋招", location: "深圳 全国", target: "2026年毕业生", position: "沃尔玛门店管培生山姆门店管培生供应链区域配送中心管培生 支持中心(总部)管培生", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://walmart.zhaopin.com/", announcementLink: "https://mp.weixin.qq.com/s/6QBod9xiiwOIO9boh4wKxA", referralCode: "-", notes: "-"},
{company: "鹏新旭", type: "央国企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "深圳", target: "2026年毕业生", position: "生产运营类研发类生产质量类IT类采购与供应链类职能类，", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://pensun.zhiye.com/campus/jobs?sessionid=", announcementLink: "https://mp.weixin.qq.com/s/SSF9krRxp7Ra5VqNx9xUgQ", referralCode: "-", notes: "要求硕士"},
{company: "东信时代", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "深圳广州珠海上海长沙 合肥 南昌 厦门杭州", target: "2026年毕业生", position: "广告优化师文案编辑信息编导广告辑师 信息流摄像师;", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://donson.zhiye.com/campus/jobs?queryId=596f8f77-3331-422d-9027-4fdb4fc40e98", announcementLink: "https://donson.zhiye.com/campus/jobs?queryId=596f8f77-3331-422d-9027-4fdb4fc40e98", referralCode: "-", notes: "-"},
{company: "赏识教育", type: "民企", industry: "教育/在线教育", recruitmentType: "秋招", location: "长沙", target: "2026年毕业生", position: "素养教育岗学科教师竞赛教练;", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/RxgKCNsEYF2mXG9uJ-XObA", announcementLink: "https://mp.weixin.qq.com/s/RxgKCNsEYF2mXG9uJ-XObA", referralCode: "-", notes: "-"},
{company: "招银网络科技-海外校园招聘", type: "央国企", industry: "IT/互联网", recruitmentType: "秋招", location: "深圳杭州成都", target: "2026年毕业生", position: "后端开发工程师 前端开发工程师 测试开发工程师 运维研发工程师;", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://cmbnt.cmbchina.com/pages/schoolRecruit/index.html", announcementLink: "https://mp.weixin.qq.com/s/mTzqttOe2nneu79kvfBeYQ", referralCode: "-", notes: "-"},
{company: "万店掌", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "苏州全国其他", target: "2026年毕业生", position: "前端开发工程师 系统开发工程师机器人工程师 嵌入式开发工程师 算法工程师(视觉方向)Java开发工程师 硬件工程师 销售新星", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://www.ovopark.com/webview/recruit2024/index.html#/job?type=1", announcementLink: "https://mp.weixin.qq.com/s/fsj6yUXJ5BXpsgr_GkjGjA", referralCode: "-", notes: "-"},
{company: "芯耀环保科技", type: "民企", industry: "电器/家电", recruitmentType: "秋招", location: "佛山", target: "2026年毕业生", position: "储备结构工程师储备电控工程师储备销售干部财务储备干部人力储备干部运营储备干部:", status: "未投递", updateTime: "2025-08-16", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/zT16VtShuH6qUS2IRsmINA", announcementLink: "https://mp.weixin.qq.com/s/zT16VtShuH6qUS2IRsmINA", referralCode: "-", notes: "-"},
{company: "中国土木", type: "央国企", industry: "建筑", recruitmentType: "秋招", location: "北京、珠海、福州、厦门、港澳地区及周边区域市场、国外", target: "2025年毕业生", position: "工程技术岗、战新产业岗、财务管理岗、外语翻译岗、法律咨询岗、行政管理岗", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/Cb43ywFrurbr-IoN9ZUYhA", announcementLink: "https://mp.weixin.qq.com/s/Cb43ywFrurbr-IoN9ZUYhA", referralCode: "-", notes: "-"},
{company: "云南师范大学", type: "事业单位", industry: "教育", recruitmentType: "秋招", location: "云南", target: "2026年毕业生", position: "教学管理人员", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://rsc.ynnu.edu.cn/", announcementLink: "https://hrss.yn.gov.cn/html/2025/8/14/62712.html", referralCode: "-", notes: "硕士研究生及以上"},
{company: "中航成飞", type: "央国企", industry: "高端装备与国防科技/航空航天", recruitmentType: "秋招", location: "成都贵州长沙西安", target: "2026年毕业生", position: "人工智能类计算机科学与技术类软件工程类控制科学与工程类电子科学与技术类航空航天类 信息与通信工程类等", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/JLe4WXgB96DyoS4h0WIF5w", announcementLink: "https://mp.weixin.qq.com/s/JLe4WXgB96DyoS4h0WIF5w", referralCode: "-", notes: "-"},
{company: "剪映CapCut", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "深圳北京上海", target: "2026年毕业生", position: "产品、运营、设计、市场", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://jobs.bytedance.com/referral/campus/pc/position/share/?token=MjsxNzU0Mzc1OTA0Njg0OzcxMTg5NDExMzM2MzUzMjM0Mjk7NzUzNDk4NjgyMDA0MDQ3NjkzNjsx&sessionid=", announcementLink: "https://mp.weixin.qq.com/s/jeEl-zBk76FjYHTfSPwHLw", referralCode: "-", notes: "-"},
{company: "太芯科技", type: "央国企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "雄安", target: "2026年毕业生", position: "芯片设计、模组设计、算法工程师、测试工程师、库房管理、产品检验;", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/_0CxxToaNJ5B0DcFPUXWBw", announcementLink: "https://mp.weixin.qq.com/s/_0CxxToaNJ5B0DcFPUXWBw", referralCode: "-", notes: "-"},
{company: "美图公司", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "厦门深圳北京", target: "2026年毕业生", position: "技术类算法类产品类运营类;", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://campus.meitu.com/campus-recruitment/meitu/54138/#/", announcementLink: "https://mp.weixin.qq.com/s/E5mjLWuhRTjT3yx9e4fKVA", referralCode: "-", notes: "-"},
{company: "芯海科技", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "深圳成都合肥西安上海", target: "2026年毕业生", position: "研发类岗位管培生岗位", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://chipsea.zhiye.com/campus", announcementLink: "https://mp.weixin.qq.com/s/xG0fdmkjOLL8h6PbxUUmfA", referralCode: "-", notes: "-"},
{company: "达发科技", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "苏州成都", target: "2026年毕业生", position: "系统软件研发工程师芯片验证工程师;", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/0ebSVeg7ZJvd37AGg0lsKA", announcementLink: "https://mp.weixin.qq.com/s/0ebSVeg7ZJvd37AGg0lsKA", referralCode: "-", notes: "-"},
{company: "蓝光智能科技", type: "民企", industry: "原材料加工/模具", recruitmentType: "秋招", location: "东莞", target: "2026年毕业生", position: "模具设计工程师、ME工程师、品质工程师电气工程师、机器人应用工程师、工艺工程师、人力资源、策略采购、IE、生产计划;", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/blovelight/45215#/", announcementLink: "https://mp.weixin.qq.com/s/ZV9pciJ4a2GM1VJzVYecDw", referralCode: "-", notes: "-"},
{company: "帆软Finestar人才专项", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "南京无锡杭州", target: "2026年毕业生", position: "产品经理 产品运营 后台开发工程师 前端开发工程师 算法工程师", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://join.fanruan.com/campus?utm_source=media&utm_medium=weixin&sessionid=", announcementLink: "https://mp.weixin.qq.com/s/m8hB4OafKRSHfQHnTTD1wg", referralCode: "-", notes: "-"},
{company: "云圣智能", type: "民企", industry: "机器人/无人机", recruitmentType: "秋招", location: "北京 天津苏州", target: "2026年毕业生", position: "算法类研发类设计类产品类解决方案类", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://ikingtec.zhiye.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/G1-Y2QKkYkSCqG9F0AO-mw", referralCode: "-", notes: "-"},
{company: "泰康之家北京分公司", type: "民企", industry: "生物制药/生命科学", recruitmentType: "秋招提前批", location: "北京", target: "2026年毕业生", position: "管家/健康照护、行政品牌、文娱运康、市场营销、经营创新、运营支持、人力资源、财务管理、医生、护士、康复治疗;", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://jobtaikang.zhiye.com/jobs?activityGuid=e2108c21-beee-4615-bba7-bb28a4be2956", announcementLink: "https://mp.weixin.qq.com/s/ZhUXCfN6gvdHTGGoSaCUPw", referralCode: "-", notes: "-"},
{company: "诺德凯", type: "民企", industry: "机械装备/电气系统", recruitmentType: "秋招", location: "苏州", target: "2026年毕业生", position: "机械类电气类软件类算法类光学类等", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/jOACbMHK46FYviwSiXNR7A", announcementLink: "https://mp.weixin.qq.com/s/jOACbMHK46FYviwSiXNR7A", referralCode: "-", notes: "-"},
{company: "中铁隧道局集团设备分公司", type: "央国企", industry: "机械装备/电气系统", recruitmentType: "秋招", location: "广州 深圳天津重庆杭州郑州等", target: "2026年毕业生", position: "机械工程机械设计制造及自动化流动体传动及控制 电气工程及其自动化 电气工程与智能控制等专业;", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/tryeB28k1DK-CzCIT0iwGg", announcementLink: "https://mp.weixin.qq.com/s/tryeB28k1DK-CzCIT0iwGg", referralCode: "-", notes: "-"},
{company: "聚宽投资", type: "民企", industry: "金融/证券", recruitmentType: "秋招", location: "北京 上海广州 深圳", target: "2026年毕业生", position: "AI算法研究员量化开发工程师 量化研究员基金运营专员 产品策略专员市场营销专员:", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/joinquant/92347?locale=zh-CN#/jobs", announcementLink: "https://mp.weixin.qq.com/s/CgcqLYQtT0s3SNU9SSr32g", referralCode: "-", notes: "-"},
{company: "TP -LINK", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "深圳杭州北京南京东莞等;", target: "2026年毕业生", position: "研发类技术市场类市场营销类制造类事行政类供应链计划类采购类财务类;", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://hr.tp-link.com.cn/?sessionid=", announcementLink: "https://mp.weixin.qq.com/s/WVb023W9qhVcbKETme2sTg", referralCode: "-", notes: "-"},
{company: "亿道集团", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "深圳上海九江北京珠海", target: "2026年毕业生", position: "算法工程师工程研究员嵌入式软件工程师硬件工程师 结构工程师热设计工程师测试工程师 产品经理 项目工程师销售岗采购程师成本工程师 会计", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://emdoor1.zhiye.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/suHRV3hQxQoo6aaeKYVWoQ", referralCode: "-", notes: "-"},
{company: "Uranus Research", type: "民企", industry: "金融/证券", recruitmentType: "秋招", location: "成都", target: "2026年毕业生", position: "C++软件开发工程师Python数据开发工程师高性能计算开发工程师 深度学习算法工程师高频量化研究员高频量化交易员;", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/k7T0s7DhP4LzeO5bH70bEg", announcementLink: "https://mp.weixin.qq.com/s/k7T0s7DhP4LzeO5bH70bEg", referralCode: "-", notes: "要求硕士"},
{company: "博康半导体", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "浙江嘉兴", target: "2026年毕业生", position: "工艺整合工程师 工艺工程师(封装)薄膜/晶背设备工程师 工艺工程师(晶圆)光刻/刻蚀设备工程师封装设备工程师生产专员，", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/qsyXdRS2-shGm4EZVPx-yA", announcementLink: "https://mp.weixin.qq.com/s/qsyXdRS2-shGm4EZVPx-yA", referralCode: "-", notes: "-"},
{company: "辉芒微电子", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "深圳", target: "2026年毕业生", position: "器件工程师模拟设计工程师 字设计工程师数字验证工程师 版图设计工程师产品验证工程师测试开发工程师电源应用工程师C用工程师 现场应用工程师(MCU);", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/rzhI771jQXEcyYGGGkKgHA", announcementLink: "https://mp.weixin.qq.com/s/rzhI771jQXEcyYGGGkKgHA", referralCode: "-", notes: "-"},
{company: "巨人网络", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "上海", target: "2026年毕业生", position: "策划类技术类美术类市场运营类职能类;", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/ztgame/92438#/jobs", announcementLink: "https://mp.weixin.qq.com/s/1yUraCRD-YUkLeSolyWGeg", referralCode: "-", notes: "-"},
{company: "卓纬律师事务所", type: "民企", industry: "商务服务/咨询", recruitmentType: "秋招", location: "北京 上海", target: "2026年毕业生", position: "争议解决部实习生、公司业务部律师、公司业务部实习生、资本市场部实习生、资本市场部实习生;", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/iVZPiKVyRHYLQEPxgSYqZQ", announcementLink: "https://mp.weixin.qq.com/s/iVZPiKVyRHYLQEPxgSYqZQ", referralCode: "-", notes: "-"},
{company: "极客未来", type: "民企", industry: "教育", recruitmentType: "秋招", location: "四川重庆广州全国", target: "2025和2026年毕业生", position: "小学教师(数学/语文)中学教师(数学/物理英语)", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://geek.m.zhiye.com/#/jobs?jc=2", announcementLink: "https://mp.weixin.qq.com/s/VQvGNSds2jOaVaHrc46XDg", referralCode: "-", notes: "-"},
{company: "科诺尔", type: "民企", industry: "原材料加工/模具", recruitmentType: "秋招", location: "烟台青岛安徽含山", target: "2026年毕业生", position: "职能类技术类生产类;", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://www.wjx.cn/vm/eSRn9av.aspx", announcementLink: "https://mp.weixin.qq.com/s/_nPe3pi5S7q30aoOYhc3VQ?poc_token=HIlXnmijARIrLxVoAmZe7t3Fo4IMythYY9R-zqZK", referralCode: "-", notes: "-"},
{company: "西门子", type: "外企", industry: "机械装备/电气系统", recruitmentType: "秋招提前批", location: "上海 大连", target: "2025和2026年毕业生", position: "西门子管理培训生项目(SGP)", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://siemens-china.tupu360.com/pageQrCode?targetUrl=a7f4739eb94ec9ef120576839eb4650abbcaa55c15715ff62393107d428a051b2d4cfa74c95209e2b84fb8d19dc7bd3a9a58ed6883da7035c331e0233f1bfbe93695d57576bb2421e91c7245da72a7436c4aab5ef73cd65618fe7b170cba1bb9d31294468bf3d0381157340b8c213c2611556771d817f208a162c187d0c56d0466c83c0612a0fc440ee762ee3af3b664308a36fb37eeb6b76f18bf0b4f08108b0669d455753ed852", announcementLink: "https://mp.weixin.qq.com/s/e3mVo55R1erLAhaXCsUx1A", referralCode: "-", notes: "-"},
{company: "远峰科技", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "东莞", target: "2026年毕业生", position: "生产品质类 结构开发类 产品管理类、算法开发类硬件开发类软件开发类项目管理类，", status: "未投递", updateTime: "2025-08-15", deadline: "招满为止", applyLink: "https://yftech2012.jobs.feishu.cn/659526/position/list?spread=MM41RWW&sessionid=", announcementLink: "https://mp.weixin.qq.com/s/Se-BvKEMtJ3JneT0vUCTiw", referralCode: "-", notes: "-"},
{company: "高标智能", type: "民企", industry: "机械装备/电气系统", recruitmentType: "秋招", location: "东莞天津重庆无锡台州徐州德国印尼", target: "2026年毕业生", position: "硬件类、供应链类、平台类;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://kjgb.zhiye.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/WL8iFqWZkJd8alBcLGd4nQ", referralCode: "-", notes: "-"},
{company: "零跑汽车", type: "民企", industry: "车企/汽车零部件", recruitmentType: "秋招", location: "杭州", target: "2026年毕业生", position: "智驾算法类、三电算法类、软件类、硬件类、大数据类、整车研发类、电池研发类、电驱研发类;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://leapmotor1.zhiye.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/WRE_hM4J_wYnleb_s2h7SA", referralCode: "-", notes: "-"},
{company: "奥比中光", type: "民企", industry: "电子/半导体", recruitmentType: "秋招", location: "佛山 深圳 上海西安", target: "2026年毕业生", position: "研发技术类岗位、产品/项目类岗位、销售类岗位、智能制造类岗位，", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://job.orbbec.com.cn/campus/jobs?sessionid=", announcementLink: "https://mp.weixin.qq.com/s/NN0YIpnXjzGEOM3yzwIJsg", referralCode: "-", notes: "-"},
{company: "微源半导体", type: "民企", industry: "电子/半导体", recruitmentType: "秋招", location: "深圳成都 上海", target: "2026年毕业生", position: "助理模拟设计工程师、助理芯片验证工程师、助理FAE;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/lowpowersemi/146943?locale=zh-CN#/", announcementLink: "https://mp.weixin.qq.com/s/t64HDMajzcVNToOevklDYA", referralCode: "-", notes: "-"},
{company: "Momenta -Mstar顶尖人才计划", type: "民企", industry: "车企/汽车零部件", recruitmentType: "秋招", location: "北京 上海苏州", target: "2026年毕业生", position: "端到端大模型算法(Mstar)、训练推理优化(Mstar);", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://momenta.jobs.feishu.cn/campus/?keywords=&category=&location=&project=7537265013606943018&type=&job_hot_flag=&current=1&limit=10&functionCategory=&tag=", announcementLink: "https://mp.weixin.qq.com/s/nLNKBsYJVVeV_TdoFRflOg", referralCode: "-", notes: "-"},
{company: "极洞科技", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "宁波 上海", target: "2026年毕业生", position: "GISS算法工程师、算法工程师、嵌入式软件工程师、硬件工程师、其他;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/11UWf-t_C518_bLPfJnUXw", announcementLink: "https://mp.weixin.qq.com/s/11UWf-t_C518_bLPfJnUXw", referralCode: "-", notes: "-"},
{company: "中电博微", type: "央国企", industry: "电子/半导体", recruitmentType: "秋招", location: "合肥", target: "2026年毕业生", position: "多种", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/Gj67-fVFC8RYxlqk4oDIPQ", announcementLink: "https://mp.weixin.qq.com/s/Gj67-fVFC8RYxlqk4oDIPQ", referralCode: "-", notes: "-"},
{company: "埃斯顿", type: "民企", industry: "机械装备/电气系统", recruitmentType: "秋招", location: "南京", target: "2026年毕业生", position: "研发类、测试类、营销类、技术类、供应链类", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://estun1.zhiye.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/zcIRLmRnmuU1RaroNWkWaQ", referralCode: "-", notes: "-"},
{company: "海光信息", type: "民企", industry: "电子/半导体", recruitmentType: "秋招", location: "北京 天津 上海无锡成都苏州", target: "2026年毕业生", position: "芯片架构/设计/验证类、软件开发/优化类、物理设计与实现类、定制/模拟电路设计类、数字中端设计/验证与实现类、工艺类、解决方案类，", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://wecruit.hotjob.cn/SU66a9aaa51eb8050c72df79f4/pb/school.html", announcementLink: "https://mp.weixin.qq.com/s/3EDoBZLj0czWgLTGb_AEnA", referralCode: "-", notes: "-"},
{company: "塞拉尼斯中国", type: "外企", industry: "石油石化/化学化工", recruitmentType: "秋招", location: "南京", target: "2026年毕业生", position: "工艺工程师、生产工程师、质量工程师、工艺控制工程师、设备工程师、可靠性工程师、环境健康安全工程师;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://xiaoyuan.zhaopin.com/company/KA0121030647P90000003000", announcementLink: "https://mp.weixin.qq.com/s/NepJPaJEuOiI9nv93dVQIA", referralCode: "-", notes: "-"},
{company: "麦楷亚洲", type: "外企", industry: "商务服务/咨询", recruitmentType: "秋招", location: "北京上海 广州 天津杭州香港纽约新加坡", target: "2026年毕业生", position: "审计岗位", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/0Os8r33kmSn6czyBsLdyMQ", announcementLink: "https://mp.weixin.qq.com/s/0Os8r33kmSn6czyBsLdyMQ", referralCode: "-", notes: "-"},
{company: "猿辅导在线教育", type: "民企", industry: "教育", recruitmentType: "秋招", location: "北京 上海", target: "2026年毕业生", position: "在线大班课明星主讲", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/6U5i9yEeTX-sAJ3lwHDoWw", announcementLink: "https://mp.weixin.qq.com/s/6U5i9yEeTX-sAJ3lwHDoWw", referralCode: "-", notes: "-"},
{company: "罗兰贝格", type: "外企", industry: "商务服务/咨询", recruitmentType: "秋招", location: "上海北京", target: "2026年毕业生", position: "初级咨询顾问", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://www.rolandberger.com/en/Join/All-Jobs/#!?countries.EN=GreaterChina", announcementLink: "https://mp.weixin.qq.com/s/V4AY3PS17BNZpowGGZrb3A", referralCode: "-", notes: "-"},
{company: "中航试金石", type: "民企", industry: "高端装备与国防科技/航空航天", recruitmentType: "秋招", location: "廊坊西安无锡盘锦", target: "2026年毕业生", position: "力学实验室试验员 结构强度工程师 热控设计工程师 模拟仿真工程师;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/7LIcc1bzs3Y5nGuIG4TMKA", announcementLink: "https://mp.weixin.qq.com/s/7LIcc1bzs3Y5nGuIG4TMKA", referralCode: "-", notes: "-"},
{company: "CVTE", type: "民企", industry: "电子/半导体", recruitmentType: "秋招", location: "广州西安合肥苏州青岛武汉全国其他", target: "2026年毕业生", position: "软件类、硬件类、职能类、商务类、制造类", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://campus.cvte.com/project/9f2877f36e9e11f0ad481070fd936d58", announcementLink: "https://mp.weixin.qq.com/s/lrz9sTnLW108G6soTKcU2w", referralCode: "-", notes: "-"},
{company: "施耐德电气", type: "外企", industry: "机械装备/电气系统", recruitmentType: "秋招提前批", location: "北京 深圳 厦门 武汉西安苏州 沈阳 呼和浩特张家口 无锡重庆", target: "2026年毕业生", position: "商业新星计划、研发新星计划、供应链新星计划;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://www.zhipin.com/zt/schneider/yanfaxinxing.html", announcementLink: "https://mp.weixin.qq.com/s/wgnWPdnxrmsdkP5FWABrPw", referralCode: "-", notes: "-"},
{company: "博世中国", type: "外企", industry: "车企/汽车零部件", recruitmentType: "秋招", location: "苏州无锡 上海杭州北京常州全国其他", target: "2026年毕业生", position: "TE/研发、SW/软件、MG/生产、BUS/商务;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/bosch/73873?sourceToken=bb908a5df522d4d48364bd1c5b01a49b&sessionid=#/jobs?page=1&anchorName=jobsList", announcementLink: "https://mp.weixin.qq.com/s/W2YglEfw8XZ8fNF06YUrwg", referralCode: "-", notes: "-"},
{company: "美团战略与投资平台", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "北京 上海", target: "2026年毕业生", position: "战略与投资分析师", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://zhaopin.meituan.com/web/position/detail?jobUnionId=3572379279&highlightType=campus&sessionid=", announcementLink: "https://mp.weixin.qq.com/s/Lp9Q_Fpw-eRG_jfLQ5eYQw", referralCode: "-", notes: "-"},
{company: "芯思原", type: "民企", industry: "电子/半导体", recruitmentType: "秋招", location: "上海成都南京海口广州", target: "2026年毕业生", position: "模拟电路设计工程师 版图设计工程师字电路设计/验证工程师数字电路后端设计工程师系统工程师嵌入式软件工程师;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://young.yingjiesheng.com/xyzlogin?ctmid=9bbee253-2703-420b-aee7-898e3302a3d2&ehirejobid=&jumpurl=httpsxyz.51job.comExternalOthersLogin51.aspxCtmID9bbee253-2703-420b-aee7-898e3302a3d2prdwww.kdocs.cnprpcdxyz.51job.comcpruidbackurlauiduuidpartner", announcementLink: "https://mp.weixin.qq.com/s/5ONPiZ7VySPMQg7EkW-74Q?scene=1", referralCode: "-", notes: "-"},
{company: "库洛游戏", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "广州 上海", target: "2026年毕业生", position: "策划类、技术类、美术类、营销类、音频类、职能类、运营类、项管类;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://kurogame.jobs.feishu.cn/campus/position/list", announcementLink: "https://mp.weixin.qq.com/s/6JsPR_6eBgzjXYE2Sw6TQQ", referralCode: "-", notes: "-"},
{company: "国盛证券", type: "央国企", industry: "金融/证券", recruitmentType: "秋招", location: "南昌北京 合肥上海", target: "2025和2026年毕业生", position: "档案管理兼文秘岗合规岗核算岗柜员岗坐席岗 人力资源岗客户经理市场开发;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/L_Vhgebf01Vttr68IOp3VA", announcementLink: "https://mp.weixin.qq.com/s/L_Vhgebf01Vttr68IOp3VA", referralCode: "-", notes: "-"},
{company: "芯迈半导体", type: "民企", industry: "电子/半导体", recruitmentType: "秋招", location: "杭州上海深圳首尔", target: "2026年毕业生", position: "研发类 运营类销售类管理类;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://campus.51job.com/SiliconMagic2025/about1.html", announcementLink: "https://mp.weixin.qq.com/s/uRhrjBagViWg2bo65uuqbw", referralCode: "-", notes: "-"},
{company: "瑞芯微电子", type: "民企", industry: "电子/半导体", recruitmentType: "秋招", location: "福州北京 上海", target: "2026年毕业生", position: "IC研发类、算法类、软件类、硬件类", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://hr.rock-chips.com/campus-recruitment/rock-chips/44102", announcementLink: "https://mp.weixin.qq.com/s/Y3XTW9pxmihcC8OXJol5Qw", referralCode: "-", notes: "-"},
{company: "vivo", type: "民企", industry: "电子/半导体", recruitmentType: "秋招", location: "东莞深圳南京上海杭州北京西海外", target: "2026年毕业生", position: "研发类市场类营销类产品运营类设计类供应链类公共类，", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://hr-campus.vivo.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/z9HbUngCGt1NiBvt4g1rmw", referralCode: "-", notes: "-"},
{company: "卡特彼勒", type: "外企", industry: "机械装备/电气系统", recruitmentType: "秋招", location: "无锡、青岛、徐州", target: "2026年毕业生", position: "研发类制造运营类产品技术类;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://careers.caterpillar.com/zh//", announcementLink: "https://mp.weixin.qq.com/s/sbOK5iOrSp-6ECLJxALXaw", referralCode: "-", notes: "-"},
{company: "华望系统科技", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "北京杭州成都西安武汉 上海", target: "2026年毕业生", position: "MBSE实施工程师MBSE售前工程师测试实施工程师 产品经理 java研发工程师;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/9GyHc9M8opQYlp5Xg2cdsQ", announcementLink: "https://mp.weixin.qq.com/s/9GyHc9M8opQYlp5Xg2cdsQ", referralCode: "-", notes: "-"},
{company: "火星人", type: "民企", industry: "电器/家电", recruitmentType: "秋招", location: "浙江嘉兴", target: "2026年毕业生", position: "技术类市场类职能类;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/marssenger1/144790?locale=zh-CN", announcementLink: "https://mp.weixin.qq.com/s/9154mce3LX_qyEoWWM3UnA", referralCode: "-", notes: "-"},
{company: "倍漾量化", type: "民企", industry: "金融/证券", recruitmentType: "秋招", location: "南京 上海", target: "2026年毕业生", position: "FPGA硬件开发工程师核心系统开发工程师机器学习算法工程师 量化策略研究员全开发工程师数据开发工程师市场渠道经理;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/TIHaV6cJSY4qnRlbGq-6VQ", announcementLink: "https://mp.weixin.qq.com/s/TIHaV6cJSY4qnRlbGq-6VQ", referralCode: "-", notes: "-"},
{company: "有道领世", type: "民企", industry: "教育", recruitmentType: "秋招", location: "北京 石家庄 广州深圳沈阳太原", target: "2026年毕业生", position: "教师管培生 线下一对一老师 线上一对一老师 线下班课老师;", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/lingshi/144566?locale=zh-CN#/", announcementLink: "https://mp.weixin.qq.com/s/EXjmKn8bd28-423254ZSCQ", referralCode: "-", notes: "-"},
{company: "东江实验室", type: "事业单位", industry: "技术服务/科学研究", recruitmentType: "秋招", location: "广东", target: "2026年毕业生", position: "成果转化管理岗、直线加速器智能化技术研发与产业化推进", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/Tws1_NOj5f6RM8d1oP2UMA", announcementLink: "https://mp.weixin.qq.com/s/Tws1_NOj5f6RM8d1oP2UMA", referralCode: "-", notes: "-"},
{company: "盐城工业职业技术学院", type: "事业单位", industry: "教育", recruitmentType: "秋招", location: "江苏", target: "2025年毕业生", position: "教师", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://rs.jshrss.jiangsu.gov.cn/index/f/RCRS_0056", announcementLink: "https://jshrss.jiangsu.gov.cn/art/2025/8/12/art_78506_11621784.html", referralCode: "-", notes: "-"},
{company: "天津市北辰区教育系统", type: "事业单位", industry: "教育", recruitmentType: "秋招", location: "天津", target: "2026年毕业生", position: "教师", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://www.tjtalents.com.cn/", announcementLink: "https://zxbm.tjtalents.com.cn/wsbm_ggfb//beifang/WebPage.aspx?id=b5964b57cf404bf1b76109358119033f", referralCode: "-", notes: "-"},
{company: "西南能矿供应链管理有限公司", type: "央国企", industry: "零售/批发", recruitmentType: "秋招", location: "贵州", target: "2026年毕业生", position: "物流管理岗、销售管理岗", status: "未投递", updateTime: "2025-08-14", deadline: "招满为止", applyLink: "https://www.gzrc.com.cn/upload/gz/Ad/2024/20240514-xn/", announcementLink: "https://www.gzrc.com.cn/upload/gz/Ad/2024/20240514-xn/", referralCode: "-", notes: "-"},
{company: "厦门航空", type: "央国企", industry: "交通运输/航空运输", recruitmentType: "秋招", location: "厦门、福州、杭州、北京、长沙等", target: "2026年毕业生", position: "安全员", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/1rEJe9nrIt-BCOwQ_-AzwA", announcementLink: "https://mp.weixin.qq.com/s/1rEJe9nrIt-BCOwQ_-AzwA", referralCode: "-", notes: "-"},
{company: "南通大学", type: "事业单位", industry: "教育", recruitmentType: "秋招", location: "南通", target: "2026年毕业生", position: "辅导员", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://rs.jshrss.jiangsu.gov.cn/index/f/RCRS_0056", announcementLink: "https://jshrss.jiangsu.gov.cn/art/2025/8/11/art_78506_11620938.html", referralCode: "-", notes: "硕士研究生及以上"},
{company: "水发集团有限公司", type: "央国企", industry: "公共设施管理/水利/环境", recruitmentType: "秋招", location: "山东", target: "2025年毕业生", position: "组织人事专员、财务专员", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "http://gzw.shandong.gov.cn/articles/ch00223/202508/b446070f-9702-49f5-86f5-8f13221e032b.html", announcementLink: "http://gzw.shandong.gov.cn/articles/ch00223/202508/b446070f-9702-49f5-86f5-8f13221e032b.html", referralCode: "-", notes: "-"},
{company: "福州港后铁路有限公司", type: "央国企", industry: "建筑/土木工程", recruitmentType: "秋招", location: "福州", target: "2026年毕业生", position: "综合办公室行政管理岗", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://gzw.fuzhou.gov.cn/zwgk/zpxx/202508/t20250811_5060141.htm", announcementLink: "https://gzw.fuzhou.gov.cn/zwgk/zpxx/202508/t20250811_5060141.htm", referralCode: "-", notes: "硕士研究生及以上"},
{company: "原力金智", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "北京", target: "2026年毕业生", position: "Cv和多模态大模型算法研究员、金融风控算法研究员;", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/mhr/144918?locale=zh-CN#/jobs?page=1&anchorName=jobsList&commitment0=", announcementLink: "https://mp.weixin.qq.com/s/c1yq31yQHGpkuKu5plSMdQ", referralCode: "-", notes: "要求硕士"},
{company: "睿励", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "上海", target: "2026年毕业生", position: "光学工程师、算法工程师、系统工程师、机械工程师、控制工程师、算法应用工程师、系统应用工程师;", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/ruili/43376#/jobs?page=1&anchorName=jobsList", announcementLink: "https://mp.weixin.qq.com/s/eRW7OBBIMmK4xsniwriHjA", referralCode: "-", notes: "-"},
{company: "芯联集成", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "上海 绍兴 深圳", target: "2026年毕业生", position: "研发类、工程技术类、职能运营类、市场销售类;", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://smec.zhiye.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/PUV6c0BfiLpE3ffn52htpg", referralCode: "-", notes: "-"},
{company: "润科通用", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "北京天津上海成都西安武汉 沈阳南昌合肥", target: "2026年毕业生", position: "系统类、硬件类、算法类、通信射频类、智能制造类、软件类、FPGA类、仿真建模类、结构设计类、销售与管理类;", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://wecruit.hotjob.cn/SU6461d2142f9d2433ba66d31d/pb/school.html", announcementLink: "https://mp.weixin.qq.com/s/lTwIw7BZrLhjPSG-TgyN4g", referralCode: "-", notes: "-"},
{company: "无锡华测电子", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "无锡 成都", target: "2026年毕业生", position: "射频工程师、测试自动化工程师、FPGA工程师、结构工程师、硬件工程师;", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/fRHgS8KjV7cF0HH45rKMJA", announcementLink: "https://mp.weixin.qq.com/s/fRHgS8KjV7cF0HH45rKMJA", referralCode: "-", notes: "-"},
{company: "新东方华南区", type: "民企", industry: "教育", recruitmentType: "秋招提前批", location: "广州 深圳 佛山 东莞珠海 南宁 海口", target: "2026年毕业生", position: "教师岗", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://zhaopin.xdf.cn/jobs?activityGuid=6052bd6f-9413-4759-82f3-8c0db60c7d11", announcementLink: "https://mp.weixin.qq.com/s/u4XdV08N9u7LvMkxRHkVFw", referralCode: "-", notes: "-"},
{company: "百奥游戏", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "广州", target: "2026年毕业生", position: "技术类、发行类、美术类、产品类;", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus_apply/aobi/25016#/", announcementLink: "https://mp.weixin.qq.com/s/ghf_pWNkAtJhcrQe4BScAw", referralCode: "-", notes: "-"},
{company: "曼胡默尔", type: "外企", industry: "车企/汽车零部件", recruitmentType: "秋招", location: "上海", target: "2026年毕业生", position: "管培生“曼芯生”、工程师学院", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/vw0gBbKSI31gkqg2VY_Gww", announcementLink: "https://mp.weixin.qq.com/s/vw0gBbKSI31gkqg2VY_Gww", referralCode: "-", notes: "-"},
{company: "联芸科技", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "杭州成都苏州广州", target: "2026年毕业生", position: "数字电路、模拟电路、嵌入式软件、介质应用、算法、硬件、测试开发、芯片测试、IT;", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/ecxb4GY15L6lEdxPiDA4Sw", announcementLink: "https://mp.weixin.qq.com/s/ecxb4GY15L6lEdxPiDA4Sw", referralCode: "-", notes: "-"},
{company: "中国航天科工集团第六研究院", type: "事业单位", industry: "高端装备与国防科技/航空航天", recruitmentType: "秋招", location: "内蒙古呼和浩特 西安 湖北远安", target: "2026年毕业生", position: "航空/航天科学技术、电子/通信与自动控制技术、计算机科学技术、机械工程、材料科学、动力与电气工程师等", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://casic.m.zhiye.com/joblist.html?jc=2&ky=&pi=1&ps=10&c1=&c2=3_35&c=", announcementLink: "https://mp.weixin.qq.com/s/AvZW6BCHqQVcOJQ-SjsZew", referralCode: "-", notes: "要求硕士"},
{company: "新芯股份", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "武汉 上海 苏州", target: "2026年毕业生", position: "研发技术类、工艺技术类、工程技术类、软件开发类、品质可靠性类;", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://whxmc.zhiye.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/UF0XWK5x6HBUkShcOGxo4Q", referralCode: "-", notes: "-"},
{company: "航天智能院", type: "央国企", industry: "高端装备与国防科技/航空航天", recruitmentType: "秋招", location: "北京", target: "2026年毕业生", position: "人工智能类、计算机科学与技术类、航空主航科学与技术类、电子科学与技术类、军事学类、仪器科学与技术类、电子信息类等", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/KGt3dY5oVjVaIe_Jc3aPqw", announcementLink: "https://mp.weixin.qq.com/s/KGt3dY5oVjVaIe_Jc3aPqw", referralCode: "-", notes: "要求硕士"},
{company: "沐瞳", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "上海杭州北京", target: "2026年毕业生", position: "技术类、美术类、产品类、发行类、职能类", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://moonton.jobs.feishu.cn/campus?sessionid=", announcementLink: "https://mp.weixin.qq.com/s/e4fkFpFNWeyRv2ds5oHBJA", referralCode: "-", notes: "-"},
{company: "点点互动", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "北京 上海福州", target: "2026年毕业生", position: "策划类、美术类、市场类、程序类、AI技术类、运营/综合类", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://ddhd.cn/campus", announcementLink: "https://mp.weixin.qq.com/s/lZs-ROI5zdvZ5XvWyybOGA", referralCode: "-", notes: "-"},
{company: "正定私募", type: "民企", industry: "金融/证券", recruitmentType: "秋招", location: "北京", target: "2026年毕业生", position: "因子研究员、策略研究员、深度学习模型研究员、交易执行算法研究员、高性能系统算法工程师、量化开发工程师、合规专员", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/zding/117879?sessionid=#/", announcementLink: "https://mp.weixin.qq.com/s/nt5mwyl0AHz7kxzwGkITqA", referralCode: "-", notes: "-"},
{company: "瑞昱半导体集团", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "苏州 合肥", target: "2026年毕业生", position: "数字IC设计类、IC验证类、模拟IC设计类、软件开发类、硬件开发类、IC Layout 类、数字后端类、设计技术研发类、AE类等;", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://www.realsil.com.cn/Home/Position", announcementLink: "https://mp.weixin.qq.com/s/wlMB5Kx1RF2O6J2kJ28b0Q", referralCode: "-", notes: "-"},
{company: "宏茂微电子", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "上海 武汉", target: "2026年毕业生", position: "技术研发类、支援职能类、生产工程类、客户品质类", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://young.yingjiesheng.com/xyzlogin?ctmid=b902c501-931b-43ad-9b9b-6797e07dc5c7&ehirejobid=&jumpurl=httpsxyz.51job.comExternalOthersLogin51.aspxCtmIDb902c501-931b-43ad-9b9b-6797e07dc5c7prdwww.kdocs.cnprpcdxyz.51job.comcpruidbackurlauiduuidpartner", announcementLink: "https://mp.weixin.qq.com/s/JaSteoa4qjjzwGc9MaaOZA", referralCode: "-", notes: "-"},
{company: "中国科学院光电技术研究所", type: "事业单位", industry: "学术科研/研究所", recruitmentType: "秋招", location: "成都", target: "2025和2026年毕业生", position: "光机类、电子与通信类、计算机与控制类、其他类专业;", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/MYxyQ8sKVASxfJErcCpg6g", announcementLink: "https://mp.weixin.qq.com/s/MYxyQ8sKVASxfJErcCpg6g", referralCode: "-", notes: "要求硕士"},
{company: "经纬恒润", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "北京 上海天津重庆合肥深圳武汉广州长春南昌南京南通成都 济宁日照 西安宁波全国其他", target: "2026年毕业生", position: "研发技术、流程IT类、研发管理、生产制造、销售服务、公共职能、供应链;", status: "未投递", updateTime: "2025-08-13", deadline: "招满为止", applyLink: "https://wecruit.hotjob.cn/SU62a93e760dcad45229a827cc/pb/school.html", announcementLink: "https://mp.weixin.qq.com/s/6CDfaeK9ZQkU88F37guLtg", referralCode: "-", notes: "-"},
{company: "亿航智能", type: "民企", industry: "机械/制造业", recruitmentType: "秋招", location: "广州", target: "2026年毕业生", position: "飞手&助理测试工程师&测试工程师,运控员&安全员", status: "未投递", updateTime: "2025-08-18", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/4LKtIYx4_kpCATfVokpfMg", announcementLink: "https://mp.weixin.qq.com/s/4LKtIYx4_kpCATfVokpfMg", referralCode: "-", notes: "-"},
{company: "天演资本", type: "民企", industry: "金融/证券", recruitmentType: "秋招", location: "上海", target: "2026年毕业生", position: "量化研究员(中低频股票,低延时期货方向),基金运营实习", status: "未投递", updateTime: "2025-08-18", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/tianyancapital/98902?locale=zh-CN#/", announcementLink: "https://mp.weixin.qq.com/s/y-htOQwmqd3Y0MzvHULYMw", referralCode: "-", notes: "-"},
{company: "武汉红星杨", type: "民企", industry: "机械/制造业", recruitmentType: "秋招", location: "武汉", target: "2026年毕业生", position: "销售工程师,机械工程师/首席科学家,光学工程师/首席科学家,精密运动控制工程师/首席科学家,软件工程", status: "未投递", updateTime: "2025-08-18", deadline: "招满为止", applyLink: "https://www.whhxykj.com/", announcementLink: "https://mp.weixin.qq.com/s/tuhIY_7F4oEXygCXWqnHpQ", referralCode: "-", notes: "-"},
{company: "中国人民健康保险", type: "央国企", industry: "金融/证券", recruitmentType: "秋招", location: "全国", target: "2026年毕业生", position: "安全管理岗,大数据分析岗,需求管理岗,规划管理岗,统计报送岗,综合审计岗,市场研究岗,经营企划岗", status: "未投递", updateTime: "2025-08-18", deadline: "招满为止", applyLink: "https://picc.zhiye.com/custom/campus?ky=&c1=&c2=130&d=-1&c=", announcementLink: "https://mp.weixin.qq.com/s/A6xniBHnCKvsQn6ps8fHlw", referralCode: "-", notes: "-"},
{company: "华安保险", type: "央国企", industry: "金融/证券", recruitmentType: "秋招", location: "全国", target: "2026年毕业生", position: "核保管理,理赔管理,客户服务!统计分析,市场营销,精算,投资研究,风险管理,法律合规,财务管理", status: "未投递", updateTime: "2025-08-18", deadline: "招满为止", applyLink: "https://xyz.51job.com/consumer/pc/home/index?ctmid=8869175", announcementLink: "https://mp.weixin.qq.com/s/1HUa0J4i3ZZeMREaGEhhmw", referralCode: "-", notes: "-"},
{company: "BCG中国区欧洲院校", type: "外企", industry: "商务服务/咨询", recruitmentType: "秋招", location: "北京 上海深圳香港台北", target: "2026年毕业生", position: "2026届欧洲院校本科生、硕士研究生、博士生和MBA", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://careers.bcg.com/global/en/job/54953", announcementLink: "https://mp.weixin.qq.com/s/Yf-ku2aQCXmQ9YKtIMRyMg", referralCode: "-", notes: "-"},
{company: "国机数字科技有限公司", type: "央国企", industry: "IT/互联网", recruitmentType: "秋招", location: "南京北京郑州", target: "2026年毕业生", position: "软件开发工程师 前端开发工程师 智能算法工程师 智能硬件工程师解决方案助理战略理岗", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://webapp.zhaopin.com/2025/hd/gjszk0814ZL68537/xJobs/index.html", announcementLink: "https://mp.weixin.qq.com/s/E32wOHBpasPQZHud7QWc4g", referralCode: "-", notes: "-"},
{company: "同道猎聘", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "北京武汉 成都杭州苏州 广州", target: "2026年毕业生", position: "产品类技术研发类运营类市场类销售类", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://www.liepin.com/logout?backUrl=httpsm.liepin.comcampusproject-detail14068724sessionid", announcementLink: "https://mp.weixin.qq.com/s/-vUkYCVUYvaFKAdupmIdcg", referralCode: "-", notes: "-"},
{company: "新国都集团", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "深圳", target: "2026年毕业生", position: "渠道助理产品经理JAVA开发工程师网络安全工程师区块链开发工程师通信嵌入式工程师;", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://app.mokahr.com/campus-recruitment/xgd/7850?sessionid=&sourceToken=9b501cf30474b6d448492f12db68c7b3#/", announcementLink: "https://mp.weixin.qq.com/s/b6BkSVGjmyveCpe3QfqTKg", referralCode: "-", notes: "-"},
{company: "中国航空制造技术研究院", type: "事业单位", industry: "学术科研/研究所", recruitmentType: "秋招", location: "北京", target: "2026年毕业生", position: "材料类机械工程类学类光学工程类自动化类化学类电子科学与技术类机械类航空字航科学与技术类 数学类等", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://avicmti.zhiye.com/campus/jobs", announcementLink: "https://mp.weixin.qq.com/s/dGnnG1-pc0rmNve_eq6Nfw", referralCode: "-", notes: "-"},
{company: "中国电科第十四研究所", type: "事业单位", industry: "学术科研/研究所", recruitmentType: "秋招", location: "南京", target: "2026年毕业生", position: "电子与通信类计算机类机械与控制类其他类;", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "http://hr.nriet.com/Pages/Job/Jobs.aspx", announcementLink: "https://mp.weixin.qq.com/s/H8dP8O9Bw_Ji2WhBM6VS4A", referralCode: "-", notes: "要求硕士"},
{company: "中国电科29所", type: "事业单位", industry: "学术科研/研究所", recruitmentType: "秋招", location: "成都", target: "2026年毕业生", position: "电子与通信类专业计算机与软件类专业控制与仪器类专业机械与工程类专业其他类专业", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://campus.51job.com/cetc29/company.html", announcementLink: "https://mp.weixin.qq.com/s/r_xbvmnHw3Hu5vMZlniKkQ", referralCode: "-", notes: "-"},
{company: "开立医疗", type: "民企", industry: "生物制药/生命科学", recruitmentType: "秋招", location: "深圳武汉北京上海", target: "2026年毕业生", position: "研发技术类 营销用服类", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://campus.sonoscape.com/campus-recruitment/sonoscape/94392/#/", announcementLink: "https://mp.weixin.qq.com/s/wvblbhGG3kGMDnZ8JJxsJQ", referralCode: "-", notes: "-"},
{company: "华为财经", type: "民企", industry: "商务服务/咨询", recruitmentType: "秋招", location: "深圳", target: "2026年毕业生", position: "财经专员", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://career.huawei.com/reccampportal/portal5/campus-recruitment-detail.html?jobId=24310&dataSource=1&jobType=0&recruitType=CR&sourceType=001", announcementLink: "https://mp.weixin.qq.com/s/74xjr0HcgRp59sm7qjmyZg", referralCode: "-", notes: "-"},
{company: "埃特曼半导体", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "厦门", target: "2026年毕业生", position: "材料外延研发材料外延材料测试机械设计电气设备装调市场营销董事长助理董事长英文助理;", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/XUkj1ImVsicuVH56Q82WLA", announcementLink: "https://mp.weixin.qq.com/s/XUkj1ImVsicuVH56Q82WLA", referralCode: "-", notes: "-"},
{company: "台达-研发岗", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "上海 武汉杭州等", target: "2026年毕业生", position: "电力电子研发设计工程师韧体控制工程师电源嵌入式软件设计工程师;", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://www.wjx.cn/vm/meczbLI.aspx", announcementLink: "https://mp.weixin.qq.com/s/LUxENTqtWuRu-ooa5YP4eA", referralCode: "-", notes: "-"},
{company: "宁德新能源", type: "民企", industry: "能源/电力", recruitmentType: "秋招", location: "宁德", target: "2026年毕业生", position: "材料/电芯研发类项目/运营类IT/大数据类博士专项机械/电气研发类智能制造类职能类 海外专项;", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://wecruit.hotjob.cn/SU5ff30f5b9b0d78e6f4283a0b/pb/school.html", announcementLink: "https://mp.weixin.qq.com/s/ffZdqoY_Mzj17ez3wQe3wA", referralCode: "-", notes: "-"},
{company: "开开华彩", type: "民企", industry: "教育", recruitmentType: "秋招", location: "北京成都", target: "2026年毕业生", position: "线上主讲类线下主讲类二讲老师类学习顾问类 运营类管培生;", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://kn50h9mzpl.jobs.feishu.cn/891492/position/list?sessionid=", announcementLink: "https://mp.weixin.qq.com/s/zz0IGP-yjHrugnF0UJsrlw", referralCode: "-", notes: "-"},
{company: "点触科技", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "厦门", target: "2026年毕业生", position: "游戏策划客服翻译营销策划 后端研发工程师测试工程师移动前端工程师 广告设计师视频设计师场景原画设计师等", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://zhaopin.dianchu.com/CampusRecruitment", announcementLink: "https://zhaopin.dianchu.com/CampusRecruitment", referralCode: "-", notes: "-"},
{company: "明汯投资", type: "民企", industry: "金融/证券", recruitmentType: "秋招", location: "香港 上海北京", target: "2026年毕业生", position: "量化研究员AI算法研究员量化开发工程师AI基础架构开发工程师", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://join.mhfunds.com/index", announcementLink: "https://mp.weixin.qq.com/s/9j-wM2GUBQR0F_Tbjt7f1w", referralCode: "-", notes: "-"},
{company: "OBSBOT寻影", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "深圳成都杭州", target: "2026年毕业生", position: "研发类非研发类管培生计划", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://www.obsbot.cn/cn/about/careers", announcementLink: "https://mp.weixin.qq.com/s/OIKoSfcBIZNbURSZtWt-pg", referralCode: "-", notes: "-"},
{company: "瑞银", type: "外企", industry: "金融/证券", recruitmentType: "秋招", location: "北京 上海", target: "2026年毕业生", position: "管理培训生", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/xrpEqltPQGpYNDadLsKEfw", announcementLink: "https://mp.weixin.qq.com/s/xrpEqltPQGpYNDadLsKEfw", referralCode: "-", notes: "-"},
{company: "度小满", type: "民企", industry: "IT/互联网", recruitmentType: "秋招", location: "北京 上海", target: "2026年毕业生", position: "算法类 研发类 产品类 运营类风险管理类商业分析类 设计类职能类;", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://campus.duxiaoman.com/051736/position/list?keywords=&category=&location=&project=7525275560747993382&type=&job_hot_flag=&current=1&limit=10&functionCategory=&tag=", announcementLink: "https://mp.weixin.qq.com/s/kFAAdWPrkGEYyQrYd6YH0w", referralCode: "-", notes: "-"},
{company: "中国电信天翼云", type: "央国企", industry: "通信服务/电信运营", recruitmentType: "秋招", location: "北京 上海广州深圳成都 厦门", target: "2026年毕业生", position: "云计算研究员后端开发工程师硬件开发工程师 客户端开发工程师 测试开发工程师解决方案经理 算法工程师等", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://wecruit.hotjob.cn/SU62b2ae672f9d24458d72f9cc/pb/school.html", announcementLink: "https://mp.weixin.qq.com/s/RWvR_-S4H6yOUcKk58GTGg", referralCode: "-", notes: "-"},
{company: "豪威集团", type: "民企", industry: "电子技术/半导体", recruitmentType: "秋招", location: "上海北京 天津 武汉成都 哈尔滨", target: "2026年毕业生", position: "数字电路设计工程师模拟IC设计工程师数字电路后端设计工程师数字验证工程师DFTI程师信号完整性工程师", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://ovt-omnivision.zhiye.com/Campus", announcementLink: "https://mp.weixin.qq.com/s/2eiOj8wkdJjrOMrtT6CA7Q", referralCode: "-", notes: "-"},
{company: "TP-Link联洲", type: "民企", industry: "通信服务/电信运营", recruitmentType: "秋招", location: "国外", target: "2026年毕业生", position: "国际业务管理培训生", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://career.tplinkglobal.com/campus/jobs?sessionid=", announcementLink: "https://mp.weixin.qq.com/s/iAwFk3Lm1PZ7z-lHiK27Vg", referralCode: "-", notes: "-"},
{company: "国仪量子", type: "民企", industry: "机械装备/电气系统", recruitmentType: "秋招", location: "合肥 广州杭州苏州无锡", target: "2026年毕业生", position: "应用工程师服务工程师客户成功经理系统工程师 结构工程师 硬件工程师软件工程师嵌入式软件工程师电子光学工程师高级系统工程师 算法工程师等", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/UsUSFs6jYp0fkqzi0T2crQ", announcementLink: "https://mp.weixin.qq.com/s/UsUSFs6jYp0fkqzi0T2crQ", referralCode: "-", notes: "-"},
{company: "海尼集团", type: "民企", industry: "电商/跨境电商", recruitmentType: "秋招", location: "厦门广州杭州", target: "2026年毕业生", position: "电商运营方向新媒体内客方向IT方向产品研发方向供应链方向市场与商务方向视觉设计方向 职能方向;", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://test-recruit.xmhaini.com/?sessionid=", announcementLink: "https://mp.weixin.qq.com/s/tcOhxQOGCYMrviI-7W7FDw", referralCode: "-", notes: "-"},
{company: "星火教育", type: "民企", industry: "教育", recruitmentType: "秋招", location: "全国", target: "2026年毕业生", position: "精品课堂教学管培生，授课学科:语文、数学、英语、物理、化学;", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://mp.weixin.qq.com/s/Qu4Tt_9t_hdSAMMw7qgUCg", announcementLink: "https://mp.weixin.qq.com/s/Qu4Tt_9t_hdSAMMw7qgUCg", referralCode: "-", notes: "-"},
{company: "飞仕得", type: "民企", industry: "能源/电力", recruitmentType: "秋招", location: "杭州", target: "2026年毕业生", position: "电力电子工程师器件工程师 上位机软件工程师硬件工程师电源工程师等", status: "未投递", updateTime: "2025-08-17", deadline: "招满为止", applyLink: "https://app135149.dingtalkoxm.com/campus-recruitment/ding-pay-yhdjz66b/100000394?locale=zh-CN#/", announcementLink: "https://mp.weixin.qq.com/s/N3H-wl8ZF1a-FPIrlUvY1A", referralCode: "-", notes: "-"},

            ];

